angalabiri/blog/urls.py
from django.urls import path

from .views import (
    PostList,
    PostDetail,
    TagDetail
)

app_name = "blog"
urlpatterns = [
    path('', PostList.as_view(), name='list'),
    path('<slug>/', PostDetail, name='detail'),
    path('tag/<slug>/', TagDetail.as_view(), name='tag'),
]

angalabiri/shop/urls.py
from django.views.generic import TemplateView, RedirectView
from django.urls import path
from angalabiri.shop.views.productviews import (
    ProductList,
    product_detail,
    ProductDownload,
)

# from angalabiri.shop.views.cartviews import cart_home, cart_update, checkout_home, checkout_done_view, cart_detail_api_view
from angalabiri.shop.views.cartviews import cart_add, cart_remove, cart_detail
from angalabiri.shop.views.orderviews import (
    OrderListView,
    OrderCreate,
    OrderDetailView,
)  # , VerifyOwnership, OrderLibraryView
from angalabiri.shop.views.billingviews import (
    payment_process,
    payment_done,
    payment_failed
)
# from angalabiri.shop.views.addressviews import (
#     AddressCreateView,
#     AddressListView,
#     AddressUpdateView,
#     checkout_address_create_view,
#     checkout_address_reuse_view,
# )

app_name = "shop"

urlpatterns = [
    path(
        "", TemplateView.as_view(template_name="shop/products/home.html"), name="home"
    ),
    path("products/", ProductList.as_view(), name="list"),
    path("products/<slug>/<int:id>", product_detail, name="detail"),
    path("products/<slug>/<int:pk>/", ProductDownload.as_view(), name="download"),
    path("cart/", cart_detail, name="cart"),
    path("cart/add/<int:product_id>/", cart_add, name="add"),
    path("cart/remove/<int:product_id>/", cart_remove, name="remove"),
    path("order/", OrderListView.as_view(), name="orders"),
    path("order/create/", OrderCreate, name="order-create"),
    path("order/<int:order_id>/", OrderDetailView.as_view(), name="order"),
    # path('order/library/', OrderLibraryView.as_view(), name='library'),
    # path("address/", RedirectView.as_view(url="/addresses")),
    # path("addresses/", AddressListView.as_view(), name="addresses"),
    # path("addresses/create/", AddressCreateView.as_view(), name="address-create"),
    # path("addresses/<int:pk>/", AddressUpdateView.as_view(), name="address-update"),
    # path(
    #     "checkout/address/create/",
    #     checkout_address_create_view,
    #     name="checkout_address_create",
    # ),
    # path(
    #     "checkout/address/reuse/",
    #     checkout_address_reuse_view,
    #     name="checkout_address_reuse",
    # ),
    path("billing/payment-method/", payment_process, name="payment_method"),
    path("billing/payment-done/", payment_done, name="payment_done"),
    path("billing/payment-canceled/", payment_failed, name="payment_failed"),
    # path(
    #     "billing/payment-method/create/",
    #     payment_method_createview,
    #     name="billing-payment-method-endpoint",
    # ),
]

angalabiri/suggestion/urls.py
from django.urls import path

from .views import (
    SuggestionList,
    SuggestionDetail,
    SuggestionCreate,
)

app_name = "suggestion"
urlpatterns = [
    path('', SuggestionList.as_view(), name='list'),
    path('create', SuggestionCreate.as_view(), name='create'),
    path('<slug>/', SuggestionDetail.as_view(), name='detail'),
]

angalabiri/users/urls.py
from django.urls import path

from angalabiri.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.documentation import include_docs_urls

from angalabiri.users.autocomplete import UsersAutocomplete
from config.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
}


def trigger_error(request):
    division_by_zero = 1 / 0
    return division_by_zero


sentry_debug = [
    path("sentry-debug/", trigger_error),
]
auto_complete_linnks = [
    path("user-autocomplete/", UsersAutocomplete.as_view(), name="user-autocomplete"),
]
admin_pages = [
    # Django Admin, use {% url 'admin:index' %}
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("jet/", include("jet.urls", namespace="jet")),
    path("jet/dashboard/", include("jet.dashboard.urls", namespace="jet-dashboard")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path(settings.ADMIN_DOC_URL, include("django.contrib.admindocs.urls")),
]

static_pages = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("the-king/", TemplateView.as_view(template_name="pages/hrh.html"), name="hrh"),
    path("the-royal-family/", TemplateView.as_view(template_name="pages/family.html"), name="fam"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
]

apps_pages = [
    # User management
    path("users/", include("angalabiri.users.urls", namespace="users")),
    path("blogs/", include("angalabiri.blog.urls", namespace="blog")),
    path("suggestion/", include("angalabiri.suggestion.urls", namespace="suggestion")),
    path("shop/", include("angalabiri.shop.urls", namespace="shop")),
    path("cause/", include("angalabiri.causes.urls", namespace="cause")),
    path("accounts/", include("allauth.urls")),
    path("comment/", include('comment.urls')),
    # Your stuff: custom urls includes go here
]

custom_pages = [
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        name="robots",
    ),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]
urlpatterns = (
    sentry_debug
    + auto_complete_linnks
    + static_pages
    + admin_pages
    + apps_pages
    + custom_pages
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    # Documentation of API
    path("api/docs/", include_docs_urls(title="Angalabir API")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

admin.site.site_header = "Angalabiri Portal"
admin.site.site_title = "Angalabiri Portal"
admin.site.index_title = "Welcome to Angalabiri Community Portal"

angalabiri/causes/forms.py
from django import forms
from angalabiri.causes.models import Cause
from ckeditor_uploader.widgets import CKEditorUploadingWidget

# from .models import Comment
import datetime


class CauseCreateForm(forms.ModelForm):
    class Meta:
        model = Cause
        exclude = ["added_by", "created", "updated", "tt_amount", "author", "slug"]

angalabiri/blog/views.py
try:
    from urllib import quote_plus  # python 2
except:
    pass

try:
    from urllib.parse import quote_plus  # python 3
except:
    pass

from django.db.models import Sum, F
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, FormMixin, UpdateView
from django.views.generic.edit import FormMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.utils.http import is_safe_url
from django.utils.safestring import mark_safe
from django.db import transaction
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.http import JsonResponse
import datetime
from sweetify.views import SweetifySuccessMixin
import sweetify
from django.utils.translation import ugettext_lazy as _
from angalabiri.blog.models import Post #, Comment
# from angalabiri.blog.forms import CommentForm
from category.models import Category, Tag
from django.contrib.contenttypes.models import ContentType

User = get_user_model()

# Create your views here.
class PostList(ListView):
    model = Post
    template_name = "pages/blog/list.html"
    ordering = ["title", "-pub_date"]
    queryset = Post.objects.all_posts()
    context_object_name = "posts"
    allow_empty = True
    paginate_by = 20
    slug_field = "slug"
    slug_url_kwarg = "slug"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        request = self.request
        tags = Tag.objects.all().filter(categories__title__iexact="News")
        context["tags"] = tags
        return context


def PostDetail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    tags = Tag.objects.all().filter(categories__title__iexact="News")

    data = {
        "post": post,
        "tags": tags
    }
    return render(request, "pages/blog/detail.html", data)


    # share_string = quote_plus(instance.content)
    # initial_data = {"content_type": instance.get_content_type, "object_id": instance.id}
    # form = CommentForm(request.POST or None, initial=initial_data)
    # if form.is_valid() and request.user.is_authenticated:
    #     c_type = form.cleaned_data.get("content_type")
    #     content_type = ContentType.objects.get(model=c_type)
    #     obj_id = form.cleaned_data.get("object_id")
    #     content_data = form.cleaned_data.get("content")
    #     parent_obj = None
    #     author = self.request.user
    #     email = self.request.user.email
    #     try:
    #         parent_id = int(request.POST.get("parent_id"))
    #     except:
    #         parent_id = None

    #     if parent_id:
    #         parent_qs = Comment.objects.filter(id=parent_id)
    #         if parent_qs.exists() and parent_qs.count() == 1:
    #             parent_obj = parent_qs.first()

    #     new_comment, created = Comment.objects.get_or_create(
    #         author=author,
    #         email=email,
    #         content_type=content_type,
    #         object_id=obj_id,
    #         content=content_data,
    #         parent=parent_obj,
    #     )
    #     return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

    # comments = instance.comments
    # tags = Tag.objects.all()
    # context = {
    #     "title": instance.title,
    #     "post": instance,
    #     "share_string": share_string,
    #     "comments": comments,
    #     "comment_form": form,
    #     "tags": tags,
    # }
    # return render(request, "pages/blog/detail.html", context)


class TagDetail(DetailView):
    model = Tag
    template_name = "pages/blog/tags.html"
    ordering = ["title", "pub_date"]
    allow_empty = True
    queryset = Post.objects.all_posts()
    context_object_name = "tag"
    slug_field = "slug"
    slug_url_kwarg = "slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tags = Tag.objects.all()
        context["tags"] = tags
        return context


































































# class PostDetail(DetailView, FormMixin):
#     model = Post
#     template_name = "pages/blog/detail.html"
#     ordering = ["title", "pub_date"]
#     allow_empty = True
#     form_class = CommentForm
#     queryset = Post.objects.all_posts()
#     context_object_name = 'post'
#     slug_field = "slug"
#     slug_url_kwarg = "slug"

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         tags = Tag.objects.all()
#         post = self.object
#         comments = post.comments.filter(active=True)
#         share_string = quote_plus(post.content)
#         context["tags"] = tags
#         context["comments"] = comments
#         context["share_string"] = share_string
#         return context

#     def get_success_url(self):
#         return reverse("blog:detail", kwargs={"slug": self.object.slug})

#     def post(self, request, *args, **kwargs):
#         form = self.get_form()
#         if form.is_valid():
#             return self.form_valid(form)
#         else:
#             return self.form_invalid(form)

#     def form_valid(self, form):
#         instance = self
#         print (instance)
#         initial_data = {
#             "content_type": instance.get_content_type,
#             "object_id": instance.id
#         }
#         if self.request.user.is_authenticated:
#             c_type = form.cleaned_data.get("content_type")
#             content_type = ContentType.objects.get(model=c_type)
#             obj_id = form.cleaned_data.get("object_id")
#             content_data = form.cleaned_data.get("text")
#             parent_obj = None
#             author = self.request.user
#             email = self.request.user.email
#             try:
#                 parent_id = int(self.request.POST.get("parent_id"))
#             except:
#                 parent_id = None

#             if parent_id:
#                 parent_qs = Comment.objects.filter(id=parent_id)
#                 if parent_qs.exists() and parent_qs.count() == 1:
#                     parent_obj = parent_qs.first()

#             new_comment, created = Comment.objects.get_or_create(
#                 author=author,
#                 email=email,
#                 content_type=content_type,
#                 object_id=obj_id,
#                 content=content_data,
#                 parent=parent_obj,
#             )
#             return HttpResponseRedirect(content_type.get_absolute_url())
#         return super().form_valid(form)

angalabiri/causes/views.py
from django.db.models import Sum, F
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DetailView, ListView
from django.views.generic.edit import (
    CreateView,
    DeleteView,
    FormMixin,
    UpdateView
)
from django.views.generic.edit import FormMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.utils.http import is_safe_url
from django.utils.safestring import mark_safe
from django.db import transaction
from django.shortcuts import get_object_or_404
from django.utils import timezone
import datetime
from sweetify.views import SweetifySuccessMixin
import sweetify
from django.utils.translation import ugettext_lazy as _
from angalabiri.causes.models import Cause
from category.models import Category, Tag

User = get_user_model()

# Create your views here.
class CauseList(ListView):
    model = Cause
    template_name = 'pages/causes.html'
    ordering = ['title', '-end_date']
    queryset = Cause.objects.all()
    context_object_name = 'causes'
    allow_empty = True
    paginate_by = 20
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        request = self.request
        tags = Tag.objects.all().filter(categories__title__iexact="Causes")
        context['tags'] = tags
        return context


class CauseDetail(DetailView):
    model = Cause
    template_name = 'pages/cause-detail.html'
    ordering = ['title', '-end_date']
    allow_empty = True
    queryset = Cause.objects.all()
    # context_object_name = 'cause'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tags = Tag.objects.all().filter(categories__title__iexact="Causes")
        context['tags'] = tags
        return context

angalabiri/templates/includes/pages/blog-css.html
{% load static compress %}

{% compress css inline %}
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/project.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/swiper.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/dark.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/font-icons.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/animate.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css" />

<link rel="stylesheet" href="{% static 'css/custom.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/calendar.css' %}" type="text/css" />

<!-- NonProfit Demo Specific Stylesheet -->
<link rel="stylesheet" href="{% static 'css/fonts.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/blog.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/modern.min.css' %}" type="text/css" />
{% endcompress %}

angalabiri/templates/includes/pages/blog-footer.html
{% load static i18n %}

<!-- Footer
		============================================= -->
<footer id="footer">

  <!-- Copyrights
			============================================= -->
  <div id="copyrights">
    <div class="container">

      <div class="row align-items-center justify-content-between col-mb-30">
        <div class="col-lg-auto text-center text-lg-left">
          Copyrights &copy; 2018 All Rights Reserved by Canvas Inc.<br>
          <div class="copyright-links"><a href="#">Terms of Use</a> / <a href="#">Privacy Policy</a></div>
        </div>

        <div class="col-lg-auto text-center text-lg-left">
          <div class="copyrights-menu copyright-links m-0">
            <a href="#">Home</a>/<a href="#">About</a>/<a href="#">Features</a>/<a href="#">Portfolio</a>/<a
              href="#">FAQs</a>/<a href="#">Contact</a>
          </div>
        </div>
      </div>

    </div>
  </div><!-- #copyrights end -->
</footer><!-- #footer end -->

angalabiri/templates/includes/pages/blog-nav.html
{% load static i18n %}

<!-- Header
		============================================= -->
<header id="header" class="header-size-custom" data-sticky-shrink="false">
  <div id="header-wrap">
    <div class="container">
      <div class="header-row justify-content-lg-between">

        <!-- Logo
						============================================= -->
        <div id="logo" class="mx-lg-auto col-auto flex-column order-lg-2 px-0">
          <a href="{% url 'home' %}" class="standard-logo" data-dark-logo="{% static 'images/logo-dark.png' %}"><img
              src="{% static 'images/logo.png' %}" alt="Angalabiri Logo"></a>
          <a href="{% url 'home' %}" class="retina-logo" data-dark-logo="{% static 'images/logo-dark@2x.png' %}"><img
              src="{% static 'images/logo@2x.png' %}" alt="Angalabiri Logo"></a>
          <span class="divider divider-center date-today"><span class="divider-text"></span></span>
        </div><!-- #logo end -->

        <div class="col-auto col-lg-3 order-lg-1 d-none d-md-flex px-0">
          <div class="social-icons">
            <a href="https://facebook.com/semicolonweb" class="social-icon si-rounded si-dark si-mini si-facebook"
              target="_blank">
              <i class="icon-facebook"></i>
              <i class="icon-facebook"></i>
            </a>
            <a href="https://twitter.com/__semicolon" class="social-icon si-rounded si-dark si-mini si-twitter"
              target="_blank">
              <i class="icon-twitter"></i>
              <i class="icon-twitter"></i>
            </a>
            <a href=" https://instagram.com/semicolonweb" class="social-icon si-rounded si-dark si-mini si-instagram"
              target="_blank">
              <i class="icon-instagram"></i>
              <i class="icon-instagram"></i>
            </a>
          </div>
        </div>

        <div class="header-misc col-auto col-lg-3 justify-content-lg-end ml-0 ml-sm-3 px-0">

          <!-- Bookmark
							============================================= -->
          <div class="dropdown dropdown-langs">
            <button class="btn dropdown-toggle px-1" type="button" id="dropdownMenuButton" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <img src="demos/seo/images/flags/eng.png" alt="French">
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
              <a href="#" class="dropdown-item"><img src="demos/seo/images/flags/fre.png" alt="Lang"> French</a>
              <a href="#" class="dropdown-item"><img src="demos/seo/images/flags/ara.png" alt="Lang"> Arabic</a>
              <a href="#" class="dropdown-item"><img src="demos/seo/images/flags/tha.png" alt="Lang"> Thailand</a>
              <a href="#" class="dropdown-item disabled" tabindex="-1" aria-disabled="true"><img
                  src="demos/seo/images/flags/eng.png" alt="Lang"> English</a>
            </div>
          </div>

          <!-- Top Search
							============================================= -->
          <div id="top-search" class="header-misc-icon">
            <a href="#" id="top-search-trigger"><i class="icon-line-search"></i><i class="icon-line-cross"></i></a>
          </div><!-- #top-search end -->

          <div class="dark-mode header-misc-icon d-none d-md-block">
            <a href="#"><i class="icon-dark"></i></a>
          </div>
        </div>

        <div id="primary-menu-trigger">
          <svg class="svg-trigger" viewBox="0 0 100 100">
            <path
              d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20">
            </path>
            <path d="m 30,50 h 40"></path>
            <path d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20">
            </path>
          </svg>
        </div>

      </div>
    </div>

    <div class="container">
      <div class="header-row justify-content-lg-center header-border">

        <!-- Primary Navigation
						============================================= -->
        <nav class="primary-menu with-arrows">

          <ul class="menu-container justify-content-between text-uppercase">
            <li class="menu-item"><a class="menu-link text-uppercase" href="{% url 'home' %}">
                <div>{% trans "Home" %}</div>
              </a></li>
              <li class="menu-item"><a class="menu-link text-uppercase" href="{% url 'shop:list' %}">
                <div>{% trans "Shop" %}</div>
              </a></li>
              <li class="menu-item current"><a class="menu-link text-uppercase" href="{% url 'blog:list' %}">
                <div>{% trans "All" %}</div>
              </a></li>
            {% for tag in tags %}
            <li class="menu-item"><a class="menu-link text-uppercase" href="{{tag.get_absolute_url}}">
                <div>{{tag.title}}</div>
              </a></li>
            {% endfor %}
          </ul>

        </nav><!-- #primary-menu end -->

        <form class="top-search-form" action="search.html" method="get">
          <input type="text" name="q" class="form-control" value="" placeholder="Type &amp; Hit Enter.."
            autocomplete="off">
        </form>

      </div>
    </div>
  </div>
  <div class="header-wrap-clone"></div>

</header><!-- #header end -->

angalabiri/templates/includes/pages/blog-totop.html
<div id="gotoTop" class="icon-angle-up rounded-circle" style="left: 30px; right: auto;"></div>

angalabiri/templates/includes/pages/nav.html
{% load static i18n %}

<!-- Header
		============================================= -->
<header id="header" class="header-size-sm border-bottom-0" data-sticky-shrink="false">
  <div id="header-wrap">
    <div class="container">
      <div class="header-row justify-content-lg-between">

        <!-- Logo
						============================================= -->
        <div id="logo" class="mr-lg-5">
          <a href="{% url 'home' %}" class="standard-logo" data-dark-logo="{% static 'images/logo-dark.png' %}"><img
              src="{% static 'images/logo.png' %}" alt="Canvas Logo"></a>
          <a href="{% url 'home' %}" class="retina-logo" data-dark-logo="{% static 'images/logo-dark@2x.png' %}"><img
              src="{% static 'images/logo@2x.png' %}" alt="Canvas Logo"></a>
        </div><!-- #logo end -->

        <div class="header-misc">
          <a href="demo-nonprofit-causes-single.html" class="button button-rounded button-light">
            <div>{% trans "Donate" %}</div>
          </a>
        </div>

        <div id="primary-menu-trigger">
          <svg class="svg-trigger" viewBox="0 0 100 100">
            <path
              d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20">
            </path>
            <path d="m 30,50 h 40"></path>
            <path d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20">
            </path>
          </svg>
        </div>

        <!-- Primary Navigation
						============================================= -->
        <nav class="primary-menu with-arrows mr-lg-auto">

          <ul class="menu-container align-self-start">
            <li class="menu-item"><span class="menu-bg col-auto align-self-start d-flex"></span></li>
            <li class="menu-item current"><a class="menu-link" href="{% url 'home' %}">
                <div>{% trans "Home" %}</div>
              </a></li>
              <li class="menu-item mega-menu mega-menu-small"><a class="menu-link" href="#"><div>About</div></a>
									<div class="mega-menu-content mega-menu-style-2">
										<div class="container">
											<div class="row">
												<ul class="sub-menu-container mega-menu-column col-lg-6">
													<li class="menu-item mega-menu-title"><a class="menu-link" href="#"><div>HRH</div></a>
														<ul class="sub-menu-container">
															<li class="menu-item"><a href="{% url 'hrh' %}">
                    <div class="widget">
                      <p class="text-uppercase ls1">Read about HRH Famous Eseduwo as we take you through his life's journey</p>
                      <img src="{% static 'images/angalabiri/king/akou2.jpg' %}" alt="HRH Famous Eseduwo" width="100px"
                        height="auto" class="img-responsive">
                    </div>
                  </a></li>
															
														</ul>
													</li>
												</ul>
												<ul class="sub-menu-container mega-menu-column col-lg-6">
													<li class="menu-item mega-menu-title"><a class="menu-link" href="#"><div>Angalabiri</div></a>
														<ul class="sub-menu-container">
															<li class="menu-item"><a class="menu-link" href="{% url 'about' %}"><div>History</div></a></li>
															<li class="menu-item"><a class="menu-link" href="{% url 'fam' %}"><div>Royalties</div></a></li>
														</ul>
													</li>
												</ul>
											</div>
										</div>
									</div>
								</li><!-- .mega-menu end -->

            <li class="menu-item"><a class="menu-link" href="{% url 'cause:list' %}">
                <div>Causes</div>
              </a>
            </li>
              <li class="menu-item"><a class="menu-link" href="{% url 'blog:list' %}">
                <div>{% trans "News" %}</div>
              </a></li>
            <li class="menu-item"><a class="menu-link" href="{% url 'shop:list' %}">
                <div>{% trans "Shop" %}</div>
              </a>
            </li>
            <li class="menu-item"><a class="menu-link" href="{% url 'suggestion:create' %}">
                <div>Suggestion Box</div>
              </a></li>
          </ul>

        </nav><!-- #primary-menu end -->

      </div>
    </div>
  </div>
  <div class="header-wrap-clone"></div>
</header><!-- #header end -->

angalabiri/templates/includes/pages/totop.html
	<!-- Go To Top
	============================================= -->
	<div id="gotoTop" class="icon-angle-up"></div>