angalabiri/blog/urls.py
from django.urls import path

from .views import (
    PostList,
    PostDetail,
    TagDetail
)

app_name = "blog"
urlpatterns = [
    path('', PostList.as_view(), name='list'),
    path('<slug>/', PostDetail, name='detail'),
    path('tag/<slug>/', TagDetail.as_view(), name='tag'),
]

angalabiri/shop/urls.py
from django.views.generic import TemplateView, RedirectView
from django.urls import path
from angalabiri.shop.views.productviews import (
    ProductList,
    product_detail,
    ProductDownload,
)

# from angalabiri.shop.views.cartviews import cart_home, cart_update, checkout_home, checkout_done_view, cart_detail_api_view
from angalabiri.shop.views.cartviews import cart_add, cart_remove, cart_detail
from angalabiri.shop.views.orderviews import (
    OrderListView,
    OrderCreate,
    OrderDetailView,
)  # , VerifyOwnership, OrderLibraryView
from angalabiri.shop.views.billingviews import (
    payment_process,
    payment_done,
    payment_failed
)
# from angalabiri.shop.views.addressviews import (
#     AddressCreateView,
#     AddressListView,
#     AddressUpdateView,
#     checkout_address_create_view,
#     checkout_address_reuse_view,
# )

app_name = "shop"

urlpatterns = [
    path(
        "", TemplateView.as_view(template_name="shop/products/home.html"), name="home"
    ),
    path("products/", ProductList.as_view(), name="list"),
    path("products/<slug>/<int:id>", product_detail, name="detail"),
    path("products/<slug>/<int:pk>/", ProductDownload.as_view(), name="download"),
    path("cart/", cart_detail, name="cart"),
    path("cart/add/<int:product_id>/", cart_add, name="add"),
    path("cart/remove/<int:product_id>/", cart_remove, name="remove"),
    path("order/", OrderListView.as_view(), name="orders"),
    path("order/create/", OrderCreate, name="order-create"),
    path("order/<int:order_id>/", OrderDetailView.as_view(), name="order"),
    # path('order/library/', OrderLibraryView.as_view(), name='library'),
    # path("address/", RedirectView.as_view(url="/addresses")),
    # path("addresses/", AddressListView.as_view(), name="addresses"),
    # path("addresses/create/", AddressCreateView.as_view(), name="address-create"),
    # path("addresses/<int:pk>/", AddressUpdateView.as_view(), name="address-update"),
    # path(
    #     "checkout/address/create/",
    #     checkout_address_create_view,
    #     name="checkout_address_create",
    # ),
    # path(
    #     "checkout/address/reuse/",
    #     checkout_address_reuse_view,
    #     name="checkout_address_reuse",
    # ),
    path("billing/payment-method/", payment_process, name="payment_method"),
    path("billing/payment-done/", payment_done, name="payment_done"),
    path("billing/payment-canceled/", payment_failed, name="payment_failed"),
    # path(
    #     "billing/payment-method/create/",
    #     payment_method_createview,
    #     name="billing-payment-method-endpoint",
    # ),
]

angalabiri/users/urls.py
from django.urls import path

from angalabiri.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.documentation import include_docs_urls

from angalabiri.users.autocomplete import UsersAutocomplete
from config.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
}


def trigger_error(request):
    division_by_zero = 1 / 0
    return division_by_zero


sentry_debug = [
    path("sentry-debug/", trigger_error),
]
auto_complete_linnks = [
    path("user-autocomplete/", UsersAutocomplete.as_view(), name="user-autocomplete"),
]
admin_pages = [
    # Django Admin, use {% url 'admin:index' %}
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("jet/", include("jet.urls", namespace="jet")),
    path("jet/dashboard/", include("jet.dashboard.urls", namespace="jet-dashboard")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path(settings.ADMIN_DOC_URL, include("django.contrib.admindocs.urls")),
]

static_pages = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("the-king/", TemplateView.as_view(template_name="pages/hrh.html"), name="hrh"),
    path("the-royal-family/", TemplateView.as_view(template_name="pages/family.html"), name="fam"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
]

apps_pages = [
    # User management
    path("users/", include("angalabiri.users.urls", namespace="users")),
    path("blogs/", include("angalabiri.blog.urls", namespace="blog")),
    path("suggestion/", include("angalabiri.suggestion.urls", namespace="suggestion")),
    path("shop/", include("angalabiri.shop.urls", namespace="shop")),
    path("cause/", include("angalabiri.causes.urls", namespace="cause")),
    path("accounts/", include("allauth.urls")),
    path("comment/", include('comment.urls')),
    # Your stuff: custom urls includes go here
]

custom_pages = [
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        name="robots",
    ),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]
urlpatterns = (
    sentry_debug
    + auto_complete_linnks
    + static_pages
    + admin_pages
    + apps_pages
    + custom_pages
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    # Documentation of API
    path("api/docs/", include_docs_urls(title="Angalabir API")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

admin.site.site_header = "Angalabiri Portal"
admin.site.site_title = "Angalabiri Portal"
admin.site.index_title = "Welcome to Angalabiri Community Portal"

angalabiri/blog/forms.py
# from dal import autocomplete
# from django import forms
# from django.contrib.auth import forms as admin_forms
# from django.contrib.auth import get_user_model
# from django.utils.translation import gettext_lazy as _

# from angalabiri.blog.models import Post, Comment

# User = get_user_model()

# from crispy_forms.helper import FormHelper
# from crispy_forms.layout import Column, HTML, Field, Fieldset, Layout, Row, Submit
# from crispy_forms.bootstrap import InlineField, UneditableField

# from crispy_forms import layout


# class CommentForm(forms.ModelForm):
#     class Meta:
#         model = Comment
#         fields = ["text"]

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.helper = FormHelper()
#         self.helper.layout = Layout(
#             Row(
#                 Column("text", css_class="form-group col-md-12"),
#                 css_class="row mb-0"
#             ),
#             HTML(
#                 "<div class='w-100'></div>",
#             ),
#             Submit(
#                 "submit",
#                 "Comment",
#                 css_class="btn btn-block text-white block rounded-lg py-3 font-weight-semibold text-uppercase mt-3 button-black"
#             )
#         )

angalabiri/blog/views.py
try:
    from urllib import quote_plus  # python 2
except:
    pass

try:
    from urllib.parse import quote_plus  # python 3
except:
    pass

from django.db.models import Sum, F
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, FormMixin, UpdateView
from django.views.generic.edit import FormMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.utils.http import is_safe_url
from django.utils.safestring import mark_safe
from django.db import transaction
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.http import JsonResponse
import datetime
from sweetify.views import SweetifySuccessMixin
import sweetify
from django.utils.translation import ugettext_lazy as _
from angalabiri.blog.models import Post #, Comment
# from angalabiri.blog.forms import CommentForm
from category.models import Category, Tag
from django.contrib.contenttypes.models import ContentType

User = get_user_model()

# Create your views here.
class PostList(ListView):
    model = Post
    template_name = "pages/blog/list.html"
    ordering = ["title", "-pub_date"]
    queryset = Post.objects.all_posts()
    context_object_name = "posts"
    allow_empty = True
    paginate_by = 20
    slug_field = "slug"
    slug_url_kwarg = "slug"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        request = self.request
        tags = Tag.objects.all().filter(categories__title__iexact="News")
        context["tags"] = tags
        return context


def PostDetail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    tags = Tag.objects.all().filter(categories__title__iexact="News")

    data = {
        "post": post,
        "tags": tags
    }
    return render(request, "pages/blog/detail.html", data)


    # share_string = quote_plus(instance.content)
    # initial_data = {"content_type": instance.get_content_type, "object_id": instance.id}
    # form = CommentForm(request.POST or None, initial=initial_data)
    # if form.is_valid() and request.user.is_authenticated:
    #     c_type = form.cleaned_data.get("content_type")
    #     content_type = ContentType.objects.get(model=c_type)
    #     obj_id = form.cleaned_data.get("object_id")
    #     content_data = form.cleaned_data.get("content")
    #     parent_obj = None
    #     author = self.request.user
    #     email = self.request.user.email
    #     try:
    #         parent_id = int(request.POST.get("parent_id"))
    #     except:
    #         parent_id = None

    #     if parent_id:
    #         parent_qs = Comment.objects.filter(id=parent_id)
    #         if parent_qs.exists() and parent_qs.count() == 1:
    #             parent_obj = parent_qs.first()

    #     new_comment, created = Comment.objects.get_or_create(
    #         author=author,
    #         email=email,
    #         content_type=content_type,
    #         object_id=obj_id,
    #         content=content_data,
    #         parent=parent_obj,
    #     )
    #     return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

    # comments = instance.comments
    # tags = Tag.objects.all()
    # context = {
    #     "title": instance.title,
    #     "post": instance,
    #     "share_string": share_string,
    #     "comments": comments,
    #     "comment_form": form,
    #     "tags": tags,
    # }
    # return render(request, "pages/blog/detail.html", context)


class TagDetail(DetailView):
    model = Tag
    template_name = "pages/blog/tags.html"
    ordering = ["title", "pub_date"]
    allow_empty = True
    queryset = Post.objects.all_posts()
    context_object_name = "tag"
    slug_field = "slug"
    slug_url_kwarg = "slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tags = Tag.objects.all()
        context["tags"] = tags
        return context


































































# class PostDetail(DetailView, FormMixin):
#     model = Post
#     template_name = "pages/blog/detail.html"
#     ordering = ["title", "pub_date"]
#     allow_empty = True
#     form_class = CommentForm
#     queryset = Post.objects.all_posts()
#     context_object_name = 'post'
#     slug_field = "slug"
#     slug_url_kwarg = "slug"

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         tags = Tag.objects.all()
#         post = self.object
#         comments = post.comments.filter(active=True)
#         share_string = quote_plus(post.content)
#         context["tags"] = tags
#         context["comments"] = comments
#         context["share_string"] = share_string
#         return context

#     def get_success_url(self):
#         return reverse("blog:detail", kwargs={"slug": self.object.slug})

#     def post(self, request, *args, **kwargs):
#         form = self.get_form()
#         if form.is_valid():
#             return self.form_valid(form)
#         else:
#             return self.form_invalid(form)

#     def form_valid(self, form):
#         instance = self
#         print (instance)
#         initial_data = {
#             "content_type": instance.get_content_type,
#             "object_id": instance.id
#         }
#         if self.request.user.is_authenticated:
#             c_type = form.cleaned_data.get("content_type")
#             content_type = ContentType.objects.get(model=c_type)
#             obj_id = form.cleaned_data.get("object_id")
#             content_data = form.cleaned_data.get("text")
#             parent_obj = None
#             author = self.request.user
#             email = self.request.user.email
#             try:
#                 parent_id = int(self.request.POST.get("parent_id"))
#             except:
#                 parent_id = None

#             if parent_id:
#                 parent_qs = Comment.objects.filter(id=parent_id)
#                 if parent_qs.exists() and parent_qs.count() == 1:
#                     parent_obj = parent_qs.first()

#             new_comment, created = Comment.objects.get_or_create(
#                 author=author,
#                 email=email,
#                 content_type=content_type,
#                 object_id=obj_id,
#                 content=content_data,
#                 parent=parent_obj,
#             )
#             return HttpResponseRedirect(content_type.get_absolute_url())
#         return super().form_valid(form)

angalabiri/causes/views.py
from django.db.models import Sum, F
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DetailView, ListView
from django.views.generic.edit import (
    CreateView,
    DeleteView,
    FormMixin,
    UpdateView
)
from django.views.generic.edit import FormMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.utils.http import is_safe_url
from django.utils.safestring import mark_safe
from django.db import transaction
from django.shortcuts import get_object_or_404
from django.utils import timezone
import datetime
from sweetify.views import SweetifySuccessMixin
import sweetify
from django.utils.translation import ugettext_lazy as _
from angalabiri.causes.models import Cause
from category.models import Category, Tag

User = get_user_model()

# Create your views here.
class CauseList(ListView):
    model = Cause
    template_name = 'pages/causes.html'
    ordering = ['title', '-end_date']
    queryset = Cause.objects.all()
    context_object_name = 'causes'
    allow_empty = True
    paginate_by = 20
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        request = self.request
        tags = Tag.objects.all().filter(categories__title__iexact="Causes")
        context['tags'] = tags
        return context


class CauseDetail(DetailView):
    model = Cause
    template_name = 'pages/cause-detail.html'
    ordering = ['title', '-end_date']
    allow_empty = True
    queryset = Cause.objects.all()
    # context_object_name = 'cause'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tags = Tag.objects.all().filter(categories__title__iexact="Causes")
        context['tags'] = tags
        return context

angalabiri/templates/includes/shop/shopcss.html
{% load static compress %}

{% compress css inline %}
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/project.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/swiper.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/dark.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/font-icons.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/animate.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css" />

<link rel="stylesheet" href="{% static 'css/custom.css' %}" type="text/css" />

<!-- NonProfit Demo Specific Stylesheet -->
<link rel="stylesheet" href="{% static 'css/ecommerce-fonts.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/ecommerce.css' %}" type="text/css" />
{% endcompress %}

angalabiri/templates/includes/shop/shopfooter.html
		<!-- Footer
		============================================= -->
		<footer id="footer" class="border-0 dark">

			<div class="container clearfix">

				<!-- Footer Widgets
				============================================= -->
				<div class="footer-widgets-wrap clearfix"  style="padding: 60px 0 100px;">

					<div class="row">
						<div class="col-lg-6 col-md-6">

							<div class="row clearfix">
								<div class="col-lg-6">
									<div class="widget widget_links widget-li-noicon">
										<h4>Hire</h4>
										<ul>
											<li><a href="#">Artisans</a></li>
											<li><a href="#">Professionals</a></li>
										</ul>
									</div>
								</div>
								<div class="col-lg-6">
									<div class="widget widget_links widget-li-noicon">
										<h4>Community</h4>
										<ul>
											<li><a href="#">Documentation</a></li>
											<li><a href="#">Feedback</a></li>
										</ul>
									</div>
								</div>
							</div>

							<div class="clear"></div>

							<div class="line line-sm"></div>

							<div class="copy-link"><a href="mailto:info@ebiangala.ng"><i class="icon-envelope2"></i>  info@ebiangala.ng</a> <span class="middot"> | </span> <a href="tel:+234 9054 16369"><i class="icon-headphones"></i> +234-9054-16369</a> <span class="middot"> | </span> <a href="skype:ebiangala?call"><i class="icon-skype2"></i> ebiangala</a></div>

						</div>

						<div class="col-lg-5 offset-lg-1">

							<div class="widget">
								<h4>Connect Socially</h4>

								<div class="bottommargin-sm clearfix">
									<a href="#" class="social-icon si-dark si-mini si-rounded si-facebook" title="Facebook">
										<i class="icon-facebook"></i>
										<i class="icon-facebook"></i>
									</a>

									<a href="#" class="social-icon si-dark si-mini si-rounded si-twitter" title="Twitter">
										<i class="icon-twitter"></i>
										<i class="icon-twitter"></i>
									</a>

									<a href="#" class="social-icon si-dark si-mini si-rounded si-instagram" title="Instagram">
										<i class="icon-instagram"></i>
										<i class="icon-instagram"></i>
									</a>

									<a href="#" class="social-icon si-dark si-mini si-rounded si-pinterest" title="Pinterest">
										<i class="icon-pinterest"></i>
										<i class="icon-pinterest"></i>
									</a>

									<a href="#" class="social-icon si-dark si-mini si-rounded si-vimeo" title="Vimeo">
										<i class="icon-vimeo"></i>
										<i class="icon-vimeo"></i>
									</a>
								</div>
							</div>

							<div class="widget subscribe-widget mt-0 clearfix">
								<h5><strong>Subscribe</strong> to Our Newsletter to get Important News, Amazing Offers &amp; Inside Scoops:</h5>
								<div class="widget-subscribe-form-result"></div>
								<form id="widget-subscribe-form" action="include/subscribe.php" method="post" class="mb-0">
									<div class="input-group input-group-lg mx-auto">
										<input type="email" id="widget-subscribe-form-email" name="widget-subscribe-form-email" class="form-control required email" placeholder="Enter your Email">
										<div class="input-group-append">
											<button class="button button-black font-weight-light button-dark ls2 text-uppercase" type="submit">Subscribe</button>
										</div>
									</div>
								</form>
							</div>

						</div>
					</div>

				</div><!-- .footer-widgets-wrap end -->

			</div>

		</footer><!-- #footer end -->

angalabiri/templates/includes/shop/shopjs.html
{% load static compress %}

{% compress js inline %}
<script src="{% static 'js/jquery.js' %}"></script>
<script defer src="{% static 'js/plugins.min.js' %}"></script>
<script src="{% static 'js/project.js' %}"></script>


<!-- Footer Scripts
============================================= -->
<script src="{% static 'js/functions.js' %}"></script>
<!-- Django Secure AJAX JS -->
<script src='{% static "js/ecommerce/csrf.ajax.js" %}'></script>

<!-- eCommerce Sales Data JS -->
<script src='{% static "js/ecommerce/ecommerce.sales.js" %}'></script>

<!-- eCommerce Custom JS -->
<script src='{% static "js/ecommerce/ecommerce.js" %}'></script>

<!-- eCommerce Main JS -->
<script src='{% static "js/ecommerce/ecommerce.main.js" %}'></script>


{% endcompress %}

angalabiri/templates/includes/shop/shopnav.html
{% load static %}

		<!-- Top Bar
		============================================= -->
		<div id="top-bar" class="dark">
			<div class="container py-3">
				<p class="center mb-0 clearfix">Corona updates for delivering to you. <a href="{% url 'shop:list' %}">Shop Now</a> | <a href="{% url 'shop:list' %}">Corona Update</a><a href="#" id="close-bar" class="float-right border-bottom-0"><i class="icon-line-cross"></i></a></p>
			</div>
		</div>

		<!-- Header
		============================================= -->
		<header id="header" class="full-header no-sticky" data-menu-padding="30">
			<div id="header-wrap">
				<div class="container">
					<div class="header-row align-items-lg-stretch">

						<!-- Logo
						============================================= -->
						<div id="logo">
							<a href="{% url 'home' %}" class="standard-logo"><img src="{% static 'images/logo.png' %}" alt="Angalabiri Logo"></a>
							<a href="{% url 'home' %}" class="retina-logo"><img src="{% static 'images/logo@2x.png' %}" alt="Angalabiri Logo"></a>
						</div><!-- #logo end -->

						<div class="header-misc align-items-lg-stretch">

							<!-- Top Cart
							============================================= -->
						<div id="top-cart" class="header-misc-icon">
								{% with total_items=cart|length %}
								<a href="#" id="top-cart-trigger"><i class="icon-line-bag"></i>
									<span class="top-cart-number">
										{% if cart|length > 0 %}{{total_items}}{% else %}0{% endif %}
									</span>
								</a>
								<div class="top-cart-content">
									<div class="top-cart-action">
										<span class="top-checkout-price">₦{% if cart|length > 0 %}{{cart.get_total_price}}{% else %}0{% endif %}</span>
										<a href="{% url 'shop:cart' %}" class="button button-3d button-small m-0">View Cart</a>
									</div>
								</div>
								{% endwith %}
							</div><!-- #top-cart end -->

							<!-- Top Account
							============================================= -->
							<div class="header-misc-icon">
								<a href="#"><i class="icon-line2-user"></i></a>
							</div>

							<!-- Top Search
							============================================= -->
							<div id="top-search" class="header-misc-icon">
								<a href="#" id="top-search-trigger"><i class="icon-line-search"></i><i class="icon-line-cross"></i></a>
							</div><!-- #top-search end -->

						</div>

						<div id="primary-menu-trigger">
							<svg class="svg-trigger" viewBox="0 0 100 100"><path d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20"></path><path d="m 30,50 h 40"></path><path d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20"></path></svg>
						</div>

						<!-- Primary Navigation
						============================================= -->
						<nav class="primary-menu style-ecommerce menu-spacing-margin">

							<ul class="menu-container">
								<li class="menu-item"><a class="menu-link" href="{% url 'home' %}"><div>Angalabiri</div></a></li>
								<li class="menu-item current mega-menu"><a class="menu-link" href="{% url 'shop:list' %}"><div>Storefront</div></a></li>
								{% comment %} <li class="menu-item mega-menu mega-menu-small"><a class="menu-link" href="#"><div>Categories</div></a>
									<div class="mega-menu-content mega-menu-style-1">
										<div class="container">
												<ul class="sub-menu-container mega-menu-column col-12">
													<li class="menu-item mega-menu-title"><a class="menu-link" href="#"><div>COMMODITIES</div></a>
														<ul class="sub-menu-container">
															{% for tag in all_cat %}
															<li class="menu-item">
																<a class="menu-link" href="{% url 'shop:list'  %}">
																	<div>{{tag.title}}</div>
																</a>
															</li>
															{% endfor %}
														</ul>
													</li>
												</ul>
										</div>
									</div>
								</li><!-- .mega-menu end --> {% endcomment %}
								<li class="menu-item"><a class="menu-link" href="{% url 'blog:list' %}"><div>Blog</div></a></li>
							</ul>

						</nav><!-- #primary-menu end -->

						<form class="top-search-form" action="search.html" method="get">
							<input type="text" name="q" class="form-control" value="" placeholder="Type &amp; Hit Enter.." autocomplete="off">
						</form>

					</div>
				</div>
			</div>
			<div class="header-wrap-clone"></div>
		</header><!-- #header end -->

angalabiri/templates/includes/shop/shoptotop.html
	<!-- Go To Top
	============================================= -->
	<div id="gotoTop" class="icon-line-arrow-up"></div>